#! /usr/bin/env ruby
require 'optparse'
require 'colorize'

VERSION = '0.1.0'.freeze

USAGE = 'Usage: echolor [options] [color] [text]'.freeze
skip_newline = false

def exit_msg msg, exit_code = 1
  puts msg
  exit exit_code
end

option_parser = OptionParser.new do |opts|
  opts.banner = USAGE

  opts.separator ''
  opts.separator 'Available option(s):'

  opts.on('-n', 'Skips newline') do
    skip_newline = true
  end

  opts.on('-v', '--version', 'Displays version') do
    exit_msg VERSION, 0
  end

  opts.separator ''

  COLORS = String.colors.join("\n\t")
  opts.separator "Available colors:\n\t#{COLORS}"
end
option_parser.parse!

color = ARGV.first
text = ARGV[1..-1].join(' ') rescue ''

exit_msg option_parser.new if color.nil?
exit_msg 'Error: Invalid color' unless String.colors.include? color.to_sym

text += "\n" unless skip_newline
print text.send color
